spring:
  application:
    name: yeohaenggaja

  # ai 관련 설정
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url:
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.5
          max-tokens: 1000

  # MySQL Connection 정보
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC